export const breeds: string[] = [
  'Mestizo / No sé',
  'Affenpinscher',
  'Afgano',
  'Airedale Terrier',
  'Akita',
  'Akita Americano',
  'Alano Español',
  'Alaskan Malamute',
  'American Bully',
  'American Foxhound',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'Antiguo Perro Pastor Inglés',
  'Appenzeller',
  'Australian Shepherd',
  'Azawakh',
  'Basset Hound',
  'Beagle',
  'Bearded Collie',
  'Beauceron',
  'Bedlington Terrier',
  'Bernés de la Montaña',
  'Bichón Frisé',
  'Bichón Habanero',
  'Bichón Maltés',
  'Bloodhound',
  'Bobtail',
  'Boerboel',
  'Border Collie',
  'Border Terrier',
  'Borzoi',
  'Boston Terrier',
  'Boxer',
  'Boyero de Flandes',
  'Braco Alemán',
  'Braco de Weimar',
  'Bull Terrier',
  'Bulldog Americano',
  'Bulldog Francés',
  'Bulldog Inglés',
  'Bullmastiff',
  'Cairn Terrier',
  'Cane Corso',
  'Caniche (Poodle)',
  'Carlino (Pug)',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chin Japonés',
  'Chow Chow',
  'Cocker Spaniel Americano',
  'Cocker Spaniel Inglés',
  'Collie',
  'Corgi Galés de Cardigan',
  'Corgi Galés de Pembroke',
  'Dálmata',
  'Doberman',
  'Dogo Argentino',
  'Dogo de Burdeos',
  'Dogo del Tíbet',
  'English Springer Spaniel',
  'Epagneul Breton',
  'Eurasier',
  'Finlandés de Laponia',
  'Fox Terrier',
  'Galgo Español',
  'Galgo Italiano',
  'Gigante de los Pirineos',
  'Golden Retriever',
  'Gran Danés',
  'Greyhound',
  'Grifón de Bruselas',
  'Husky Siberiano',
  'Irish Wolfhound',
  'Jack Russell Terrier',
  'Keeshond',
  'Kerry Blue Terrier',
  'Komondor',
  'Kuvasz',
  'Labrador Retriever',
  'Lakeland Terrier',
  'Leonberger',
  'Lhasa Apso',
  'Malamute de Alaska',
  'Mastín Español',
  'Mastín Napolitano',
  'Mastín Tibetano',
  'Mudi',
  'Münsterländer',
  'Papillón',
  'Pastor Alemán',
  'Pastor Australiano',
  'Pastor Belga',
  'Pastor Blanco Suizo',
  'Pastor de Anatolia',
  'Pastor de Beauce',
  'Pastor de Brie',
  'Pastor de los Pirineos',
  'Pastor de Shetland',
  'Pekinés',
  'Perro de Agua Español',
  'Perro de Agua Portugués',
  'Perro Lobo Checoslovaco',
  'Pinscher Miniatura',
  'Podenco Ibicenco',
  'Pointer',
  'Pomerania',
  'Presa Canario',
  'Puli',
  'Rhodesian Ridgeback',
  'Rottweiler',
  'Saluki',
  'Samoyedo',
  'San Bernardo',
  'Schnauzer',
  'Schnauzer Gigante',
  'Schnauzer Miniatura',
  'Scottish Terrier',
  'Setter Irlandés',
  'Shar Pei',
  'Shiba Inu',
  'Shih Tzu',
  'Silky Terrier',
  'Spitz Alemán',
  'Staffordshire Bull Terrier',
  'Teckel (Dachshund)',
  'Terranova',
  'Terrier Australiano',
  'Terrier Escocés',
  'Terrier Irlandés',
  'Terrier Tibetano',
  'Vizsla',
  'Volpino Italiano',
  'Weimaraner',
  'West Highland White Terrier',
  'Whippet',
  'Xoloitzcuintle',
  'Yorkshire Terrier'
];
